name: CI/CD Example
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start

        name: report run
        run: npm run report:merge
        name: report merge
      - run: npm run report:mocha
      - name: Reports deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
            BRANCH: main
            FOLDER: mochawesome-report
        timeout-minutes: 10      
